<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-11-09 15:30

$extensionClassesPath = t3lib_extMgm::extPath('meta_feedit') . 'Classes/';
return array(
'tx_metafeedit_lib_pidhandler'=>$extensionClassesPath . 'Lib/PidHandler.php',
'phpexcel_writer_excel2007'=>t3lib_extMgm::extPath('meta_feedit') . 'lib/PHPExcel/Writer/Excel2007.php'
);
?>