<?php
/**
 * Language labels for extension "mth_feedit"
 *
 */
$LOCAL_LANG = Array (
	'default' => Array (
		'total' => 'Total',
		'pi1_title' => 'FE Edition Meta',
		'pi1_plus_wiz_description' => 'Adds a frontend form for submitting and editing of tables to your page',
		'back_label' => 'Back',
		'new_label' => 'New',
		'fulltext_search' => 'Fulltext search',
		'alphabetical_search' => 'Alphabetical search',
		'calendar_search' => 'Calendar search',
		'fulltext_search' => 'Fulltext search',
		'order_by' => 'Ordered by',
		'login_required_message' => 'Frontend login is required to view this page',
		'edit_header_prefix' => 'Editing of',
		'grid_rows_cols' => 'Rows / Cols ',
		'grid_header' => 'Data Grid',
		'crdate' => 'Creation date',
		'uid' => 'Unique Identifier',
		'pid' => 'Page ID',
		'sorting' => 'Sorting Index',
		'edit_grid_description' => 'You may edit Grid Data here',
		'edit_delete_label' => 'Delete',
		'edit_order_up_label' => 'Move up Record',
		'edit_order_down_label' => 'Move down Record',
		'edit_delete_confirm' => 'Are you sure?',
		'edit_saved_header' => 'Saved',
		'edit_saved_message' => 'Your record has been saved',
		'edit_preview_submit_label' => 'Save changes',
		'edit_preview_donotsave_label' => 'Go Back',
		'edit_submit_label' => 'See Preview',
		'edit_menu_header' => 'Edit menu',
		'edit_link' => 'Edit record',
		'filtre_recherche' => 'Search Filter',
		'filtre_lettre' => 'Alphabetical Filter',
		'blog_header' => 'Comments of ',
		'blog_new_comment' => 'Leave a comment',
		'blog_submit_label' => 'Leave my comment',
		'blog_captcha_error' => 'The anti-spam value is not the one shown in the image',
		'link-edit' => 'Edit record',
		'link-consult' => 'View this record',
		'edit_menu_description' => 'List of items',
		'edit_menu_noitems_header' => 'No items aval.',
		'edit_menu_noitems_description' => 'Sorry, there where no items available.',
		'edit_menu_createnew_label' => 'Create new record',
		'alphabetical_search_all' => 'All',
		'advanced_search_label' => 'Search',
		'advanced_search_reset' => 'Reset search criteria',
		'order_by_reset' => 'Reset order by',
		'add_image_tooltip' => 'Click here to browse your computer for a file to upload',
		'delete_image_tooltip' => 'Click here to delete a file you selected in the panel. To delete effectively you must save the modification ',
		'create_header_prefix' => 'Create ',
		'create_saved_header' => 'Added',
		'create_saved_message' => 'Your record has been added',
		'create_preview_submit_label' => 'Submit record',
		'create_preview_donotsave_label' => 'Do Not Save',
		'create_edit_link' => 'Edit a record',
		'create_submit_label' => 'See Preview',
		'delete_saved_header' => 'Deleted',
		'delete_saved_message' => 'The record has been deleted',
		'delete_preview_header' => 'Really want to delete the record?',
		'delete_preview_message' => 'If you delete the record it will be gone forever. So make sure you relly want to delete it?',
		'delete_preview_delete_label' => 'Yes, delete the record.',
		'delete_preview_dont_delete_label' => 'No, let me get back.',
		'required_message' => 'This field is required',
		'error_file_size' => 'Size is beyond %s kb ( %s bytes) and the file cannot be saved.',
		'error_file_upload' => 'Surprisingly there was no file for %s in %s',
		'error_file_extension' => 'Extension %s not allowed',
		'error_file_pattern' => 'Filename matched illegal pattern.',
		'error_no_upload_path' => 'No upload path defined !',
		'error_occured' => 'An error has arised, check your fields please',
		'error_mvalue_existed'=>'A record with the same values exists already. Maybe you clicked twice ...',
		'error_value_existed'=>'The value existed already. Enter a new value.',
		'error_value_twice'=>'You must enter the same value twice',
		'error_valid_email'=>'You must enter a valid email address',
		'error_value_required'=>'You must enter a value!',
		'error_max_char'=>'You must enter at most %s characters!',
		'error_min_char'=>'You must enter at least %s characters!',
		'error_value_notInList'=>'The value was not a valid value from this list: %s',
		'error_required'=>'A requested field is empty, check your fields !',
		'blogcomments' => 'Comments',
		'monday' => 'Monday',
		'tuesday' => 'Tuesday',
		'wednesday' => 'Wednesday',
		'thursday' => 'Thursday',
		'friday' => 'Friday',
		'saturday' => 'Saturday',
		'sunday' => 'Sunday',
		'view_posts' => 'View posts for %s',
		'calReset' => 'Reset',
		'check_yes' => 'Yes',
		'check_no' => 'No',
		'search_nothing' => 'None',
		'move_top' => 'Move selected items to top',
		'move_up' => 'Move selected items upwards',
		'move_bt' => 'Move selected items downwards',
		'move_down' => 'Move selected items to bottom',
		'move_delete' => 'Delete selected items',
		'printedby' => 'Printed by : ',	),
	'dk' => Array (
		'create_header_prefix' => 'Tilføjer ',
	),
	
	// German version thanks to Ralf Thierfelder [ralfthierfelder@gmx.de]
	'de' => Array (		
		'pi1_title' => 'FE Edition Meta',
        'pi1_plus_wiz_description' => 'Fügt ihrer Seite ein Frontend-Formular zum Eingeben und Bearbeiten von Daten hinzu.',
		'back_label' => 'Zurück',
		'login_required_message' => 'Sie müssen sich einloggen, damit diese Seite angezeigt wird.',
		'edit_header_prefix' => 'Bearbeiten: ',
		'edit_delete_label' => 'Lösche Datensatz',
		'edit_delete_confirm' => 'Sind Sie sicher?',
		'edit_saved_header' => 'Gespeichert',
		'edit_saved_message' => 'Ihre Eingabe wurde gespeichert.',		
		'edit_preview_submit_label' => 'Änderungen speichern',
		'edit_preview_donotsave_label' => 'Zurück',
		'edit_submit_label' => 'Vorschau',
		'edit_menu_header' => 'Änderungen',
		'edit_link' => 'Datensatz bearbeiten',
		'link-edit' => 'Datensatz bearbeiten',
		'link-consult' => 'Datensatz ansehen',
		'edit_menu_description' => 'Auflistung',
		'edit_menu_noitems_header' => 'Keine Daten verfügbar',
		'edit_menu_noitems_description' => 'Es stehen keine Daten zur Verfügung.',
		'edit_menu_createnew_label' => 'Neuen Datensatz anlegen',
		'advanced_search_label' => 'Suche',
		'advanced_search_reset' => 'Löschen',
		'add_image_tooltip' => 'Klicken Sie hier, um eine Datei zum Hochladen auszuwählen.',
		'delete_image_tooltip' => 'Klicken Sie hier, um eine Datei zu löschen, die sie im Panel ausgewählt haben. Sie müssen die Änderungen speichern, um wirksam zu löschen.',		
		'create_header_prefix' => 'Erstelle ',
		'create_saved_header' => 'Hinzugefügt',
		'create_saved_message' => 'Ihr Datensatz wurde hinzugefügt.',
		'create_preview_submit_label' => 'Speichern',
		'create_preview_donotsave_label' => 'Nicht speichern',
		'create_edit_link' => 'Datensatz bearbeiten',
		'create_submit_label' => 'Vorschau',
		'delete_saved_header' => 'Gelöscht',
		'delete_saved_message' => 'Der Datensatz wurde gelöscht',
		'delete_preview_header' => 'Wollen Sie den Datensatz löschen?',
		'delete_preview_message' => 'Der Löschvorgang kann nicht rückgängig gemacht werden!',
		'delete_preview_delete_label' => 'Ja, Datensatz löschen.',
		'delete_preview_dont_delete_label' => 'Nein, löschen abbrechen.',		
		'required_message' => 'Dieses Feld muss ausgefüllt werden',
		'error_file_size' => 'Die Dateigröße beträgt mehr als %s kb ( %s bytes). Die Datei kann daher nicht gespeichert werden.',
		'error_file_upload' => 'Die Datei für %s existiert nicht in %s.',
		'error_file_extension' => 'Die Dateiendung %s ist nicht erlaubt.',
		'error_file_pattern' => 'Der Dateiname ist nicht erlaubt.',
		'error_no_upload_path' => 'Der Upload-Pfad ist nicht definiert!',
		'error_occured' => 'Es ist ein Fehler aufgetreten. Bitte überprüfen Sie die Eingabefelder.',
		'error_value_existed'=>'Der Wert besteht bereits. Bitte geben Sie einen neuen Wert ein.',
		'error_value_twice'=>'Sie müssen den gleichen Wert zweimal eingeben.',
		'error_valid_email'=>'Sie müssen eine existierende Email-Adresse eingeben.',
		'error_value_required'=>'Sie müssen einen Wert eingeben!',
		'error_max_char'=>'Sie dürfen höchstens %s Zeichen eingeben!',
		'error_min_char'=>'Sie müssen mindestens %s Zeichen eingeben!',
		'error_value_notInList'=>'Der Wert ist kein gültiger Wert aus dieser Liste: %s',
		'error_required'=>'Ein Pflichtfeld ist leer. Bitte überprüfen Sie die Eingabe!',
		'monday' => 'Montag',
		'tuesday' => 'Dienstag',
		'wednesday' => 'Mittwoch',
		'thursday' => 'Donnerstag',
		'friday' => 'Freitag',
		'saturday' => 'Samstag',
		'sunday' => 'Sonntag',
		'view_posts' => 'Zeige Posts aus %s',

	),
	'no' => Array (
		'monday' => 'Mandag',
		'tuesday' => 'Tirsdag',
		'wednesday' => 'Onsdag',
		'thursday' => 'Torsdag',
		'friday' => 'Fredag',
		'saturday' => 'Lørdag',
		'sunday' => 'Søndag',
		'view_posts' => 'Vis alle poster for %s',

	),
	'it' => Array (
	),
	'fr' => Array (	
		'total' => 'Total',
		'crdate' => 'Date de création',
		'uid' => 'identifiant unique',
		'sorting' => 'index de tri',
		'pid' => 'ID de page',
		'ascending' => 'ascendant',
		'descending' => 'descendant',
		'pid' => 'ID de page',
		'tstamp' => 'Date de modification',
		'fulltext_search' => 'Recherche plein texte',
		'alphabetical_search' => 'Recherche alphabétique',
		'calendar_search' => 'Recherche calendaire',
		'order_by' => 'Ordonné par',
		'pi1_title' => 'FE Edition Meta',
		'pi1_plus_wiz_description' => 'Adds a frontend form for submitting and editing of tables to your page.',
		'pi_list_browseresults_displays'=>'Affichage des enregistrements ###SPAN_BEGIN###%s &agrave; %s</span> sur ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search'=>'Chercher',
		'pi_list_browseresults_prev' =>'< Précédent',
		'pi_list_browseresults_next'=>'Suivant >',
		'pi_list_browseresults_page'=> 'Page',
		'pi1_title' => 'FE Edition Meta',
		'grid_rows_cols' => 'Lignes / Colonnes ',
		'grid_header' => 'Data Grid',
		'edit_grid_description' => 'Vous pouvez &eacute;diter les informations de la grille ici',
		'back_label' => 'Retour',
		'new_label' => 'Nouveau',
		'login_required_message' => 'Vous devez &ecirc;tre connect&eacute; pour voir cette page.',
		'filtre_recherche' => 'Filtre Recherche',
		'filtre_lettre' => 'Filtre alphabétique',
		'blog_header' => 'Commentaires de ',
		'blog_new_comment' => 'Laisser un commentaire',
		'blog_submit_label' => 'Laisser mon commentaire',
		'blog_captcha_error' => 'La valeur anti-spam saisie n\'est pas celle de l\'image',
		'edit_header_prefix' => 'Edition de',
		'edit_delete_label' => 'Supprimer',
		'edit_order_up_label' => 'Monter',
		'edit_order_down_label' => 'Descendre',
		'edit_delete_confirm' => '&Ecirc;tes vous s&ucirc;r ?',
		'edit_saved_header' => 'Enregistr&eacute;',
		'edit_saved_message' => 'Vos informations ont &eacute;t&eacute; mises &agrave; jour.',
		'edit_preview_submit_label' => 'Mettre &agrave; jour',
		'edit_preview_donotsave_label' => 'Annuler',
		'edit_submit_label' => 'Pr&eacute;visualiser',
		'advanced_search_label' => 'Recherche',
		'advanced_search_reset' => 'Enlever critères de recherche',
		'order_by_reset' => 'Enlever tri',
		'actions' => 'Actions',
		'alphabetical_search_all' => 'Tous',
		'edit_menu_header' => 'Liste des &eacute;l&eacute;ments',
		'edit_menu_description' => 'Modifiez ou consultez vos enregistrements ci dessous',
		'edit_menu_noitems_header' => 'Aucun &eacute;l&eacute;ment',
		'edit_menu_noitems_description' => 'Il n\'y a aucun &eacute;l&eacute;ment &agrave; &eacute;diter.',
		'edit_link' => 'Editer',
		'link-edit' => 'Editer',
		'link-consult' => 'Consulter',
		'error_file_size' => 'La taille du fichier (%2$s octets) est sup&eacute;rieure au maximum autoris&eacute; : %1$s Ko, le fichier ne peut &ecirc;tre enregistr&eacute;',
		'error_file_upload' => 'Le fichier %s est introuvable dans %s',
		'error_file_extension' => 'L\'extension %s n\'est pas autoris&eacute;e',
		'error_file_pattern' => 'Le nom du fichier suit un motif interdit.',
		'error_no_upload_path' => 'Le chemin d\'upload n\'est pas d&eacute;fini',
		'error_occured' => 'Une erreur s\'est produite,v&eacute;rifiez vos champs',
		'error_mvalue_existed'=>'Un enregistrement a d&eacute;j&agrave; &eacute;t&eacute; saisi avec les m&ecirc;mes valeurs. Peut &ecirc;tre avez vous cliqu&eacute; 2 fois ... Saisissez une autre valeur ',
		'error_value_existed'=>'Cette valeur existe d&eacute;j&agrave; et doit &ecirc;tre unique. Saisissez une autre valeur ',
		'error_value_twice'=>'Les valeurs saisies ne sont pas les m&ecirc;mes, vous devez saisir la m&ecirc;me valeur deux fois.',
		'error_valid_email'=>'Vous devez saisir une adresse de courriel valide',
		'error_value_required'=>'Vous devez saisir une valeur',
		'error_max_char'=>'Ce champ ne peut d&eacute;passer %s caract&egrave;res.',
		'error_min_char'=>'Ce champ doit contenir un minimum de %s caract&egrave;res.',
		'error_value_notInList'=>'Cette valeur n\'est pas une valeur valide de cette liste: %s',
		'error_required'=>'Un champ requis est vide, v&eacute;rifiez vos champs',
		'edit_menu_createnew_label' => 'Nouvel &eacute;l&eacute;ment',
		'add_image_tooltip' => 'Cliquez ici pour ouvrir une fen&ecirc;tre de s&eacute;lection de fichiers sur votre ordinateur. Il faut ensuite mettre &agrave; jour l\'enregistrement pour que la modification soit prise en compte',
		'delete_image_tooltip' => 'Cliquez ici pour supprimer un fichier de la boite de s&eacute;lection de gauche. Pour effectuer la suppression vous devez mettre &agrave; jour ensuite l\'enregistrement',
		'create_header_prefix' => 'Cr&eacute;er',
		'create_saved_header' => 'Ajout&eacute;',
		'create_saved_message' => 'Votre soumission a &eacute;t&eacute; ajout&eacute;e',
		'create_preview_submit_label' => 'Soumettre',
		'create_preview_donotsave_label' => 'Annuler',
		'create_edit_link' => 'Editer',
		'create_submit_label' => 'Pr&eacute;visualiser',
		'delete_saved_header' => 'Supprim&eacute;',
		'delete_saved_message' => 'Votre enregistrement a &eacute;t&eacute; supprim&eacute;.',
		'delete_preview_header' => 'Voulez vous vraiment supprimer cet enregistrement ?',
		'delete_preview_message' => 'Si vous supprimez cet enregistrement il sera irr&eacute;m&eacute;diablement perdu. &Ecirc;tes vous certain de vouloir le supprimer?',
		'delete_preview_delete_label' => 'Oui, je veux supprimer mon enregistrement.',
		'delete_preview_dont_delete_label' => 'Non, je veux revenir &agrave; l&acute;edition de mes donn&eacute;es.',
		'required_message' => 'Ce champ est requis.',
		'blogcomments' => 'Commentaires',
		'monday' => 'Lundi',
		'tuesday' => 'Mardi',
		'wednesday' => 'Mercredi',
		'thursday' => 'Jeudi',
		'friday' => 'Vendredi',
		'saturday' => 'Samedi',
		'sunday' => 'Dimanche',
		'view_posts' => 'Voir les enregistrements pour %s',
		'calReset' => 'Tout voir',
		'check_yes' => 'Oui',
		'check_no' => 'Non',
		'search_nothing' => 'Aucun',
		'move_top' => 'Déplacer vers le haut les éléments sélectionnés',
		'move_up' => 'Déplacer l\'élément vers le haut',
		'move_bt' => 'Déplacer l\'élément vers le bas',
		'move_down' => 'Déplacer l\'élément en bas',
		'move_delete' => 'Supprimer les éléments sélectionnés',
		'printedby' => 'Imprimé par : ',

	),
	'es' => Array (
	),
	'nl' => Array (
		'monday' => 'Maandag',
		'tuesday' => 'Dinsdag',
		'wednesday' => 'Woensdag',
		'thursday' => 'Donderdag',
		'friday' => 'Vrijdag',
		'saturday' => 'Zaterdag',
		'sunday' => 'Zondag',
		'view_posts' => 'Bekijk berichten voor %s',

	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
		'monday' => 'Ïîíåäåëüí&egrave;&ecirc;',
		'tuesday' => 'Âòîðí&egrave;&ecirc;',
		'wednesday' => 'Ñðåä&agrave;',
		'thursday' => '×åòâåðã',
		'friday' => 'Ïÿòí&egrave;ö&agrave;',
		'saturday' => 'Ñóááîò&agrave;',
		'sunday' => 'Âîñ&ecirc;ðåñåíüå',
		'view_posts' => 'Ïðîñìîòðåòü ïîñòû îò %s',

	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>