<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'meta_feedit.pi_flexform.feeditevalvalues' => 'Edit eval Values',
	  	'meta_feedit.pi_flexform.fecreateevalvalues' => 'Create eval Values',
	   	'meta_feedit.pi_flexform.editPreview' => 'Edit Preview',
	   	'meta_feedit.pi_flexform.gridAjax' => 'Grid',
		'meta_feedit.pi_flexform.gridEdit' => 'Edit',
		'meta_feedit.pi_flexform.sheet_general' => 'General Settings',
		'meta_feedit.pi_flexform.sheet_cal' => 'Calendar mode Settings',

		'meta_feedit.pi_flexform.sheet_quickstart' => 'Quick Start',
		'meta_feedit.pi_flexform.sheet_create' => 'Create',
		'meta_feedit.pi_flexform.sheet_edit' => 'Edit',
		'meta_feedit.pi_flexform.idField' => 'Id Field',
		'meta_feedit.pi_flexform.advancedSearch' => 'Advanced Search',
		'meta_feedit.pi_flexform.advancedSearchFields' => 'Advanced Search Fields (default list fields)',
		'meta_feedit.pi_flexform.advancedSearchAjaxSelector' => 'Advanced Search Ajax Selectors',
		'meta_feedit.pi_flexform.calendarSearch' => 'Calendar Search',
		'meta_feedit.pi_flexform.alphabeticalSearch' => 'Alphabetical Search',
		'meta_feedit.pi_flexform.categorySearch' => 'Category Search',
		'meta_feedit.pi_flexform.sheet_edit' => 'Edit',
		'meta_feedit.pi_flexform.foreignTables' => 'Foreign Tables',
		'meta_feedit.pi_flexform.defaultCmd' => 'Default command',
		'meta_feedit.pi_flexform.defaultCmd.auto' => 'Auto',
		'meta_feedit.pi_flexform.defaultCmd.create' => 'Create',
		'meta_feedit.pi_flexform.defaultCmd.edit' => 'Edit',
		'meta_feedit.pi_flexform.page' => 'Page with records',
		'meta_feedit.pi_flexform.xhtml' => 'XHTML compliancy',
		'meta_feedit.pi_flexform.referenceMetafeedit' => 'Reference MetaFeEdit (DB select)',
		'meta_feedit.pi_flexform.referenceMetafeeditText' => 'Reference MetaFeEdit (uid in clear text)',
		'meta_feedit.pi_flexform.referenceKeyExclude' => 'Reference Excluded Fields',
		'meta_feedit.pi_flexform.referenceExcludeDbRelation' => 'Reference Excluded DB Relation',
		'meta_feedit.pi_flexform.sheet_debug' => 'Debug',
		'meta_feedit.pi_flexform.debugSQL' => 'Generated SQL',
		'meta_feedit.pi_flexform.debugKrumo' => 'Use Krumo to debug (requires extension Krumo)',
		'meta_feedit.pi_flexform.debugMarkerArray' => 'Marker Array',
		'meta_feedit.pi_flexform.debugLangArray' => 'Lang Array',
		'meta_feedit.pi_flexform.debugConf' => 'Conf',
		'meta_feedit.pi_flexform.debugPerformances' => 'Performances',
		'meta_feedit.pi_flexform.debugTemplate' => 'Template',
		'meta_feedit.pi_flexform.debugVars' => 'POST,GET, PiVars... Variables',
		'meta_feedit.pi_flexform.debugTSFE' => 'TSFE',
		'meta_feedit.pi_flexform.disableDelete' => 'Disable delete',
		'meta_feedit.pi_flexform.disableEditDelete' => 'Disable Edit delete',
		'meta_feedit.pi_flexform.defaultListMode' => 'Default List Mode',
		'meta_feedit.pi_flexform.defaultListMode.list' => 'List',
		'meta_feedit.pi_flexform.defaultListMode.calendar' => 'Calendar',
		'meta_feedit.pi_flexform.defaultListMode.datagrid' => 'Data Grid',
		'meta_feedit.pi_flexform.requireLogin' => 'Require that a user is logged in',
		'meta_feedit.pi_flexform.no_header' => 'Dont display automatic generated headers',
		'meta_feedit.pi_flexform.show_help_icons' => 'Show help icons (if availiable)',
		'meta_feedit.pi_flexform.allowedGroups' => 'Allowed editor groups',
		'meta_feedit.pi_flexform.clearCacheOfPages' => 'Pages to clear cache of',
		'meta_feedit.pi_flexform.disableCreate' => 'Disable create',
		'meta_feedit.pi_flexform.hideCreate' => 'Hide create',
		'meta_feedit.pi_flexform.hideEdit' => 'Hide edit',
		'meta_feedit.pi_flexform.hideDelete' => 'Hide delete',
		'meta_feedit.pi_flexform.noSpecialLoginForm' => 'Show no special form when logged in',
		'meta_feedit.pi_flexform.fetable' => 'Table to edit',
		'meta_feedit.pi_flexform.previewnoemptyfields' => 'No Empty Fields',
		'meta_feedit.pi_flexform.backPagePid' => 'Back Page Pid',
		'meta_feedit.pi_flexform.editBackPagePid' => 'Back Page Pid',
		'meta_feedit.pi_flexform.fecreatefields' => 'Creation Fields',
		'meta_feedit.pi_flexform.feparsevalues' => 'parseValues', 
		'meta_feedit.pi_flexform.groupBySize' => 'Group By Size (for vertical display)',
		'meta_feedit.pi_flexform.displaydirection' => 'Display direction',
		'meta_feedit.pi_flexform.editlangmarks' => 'Language marks (lg.label=val)',
		'meta_feedit.pi_flexform.createlangmarks' => 'Language marks (lg.label=val)',
		'meta_feedit.pi_flexform.rUJoinField' => 'rU Join Field',
		'meta_feedit.pi_flexform.noUserCheck' => 'No User Check',
		'meta_feedit.pi_flexform.editUserCheck' => 'User Check',
	  'meta_feedit.pi_flexform.deleteUserCheck' => 'User Check',
	  'meta_feedit.pi_flexform.deleteGroupCheck' => 'Group Check',
	  'meta_feedit.pi_flexform.editGroupCheck' => 'Group Check',
		'meta_feedit.pi_flexform.fe_userOwnSelf' => 'Fe User Own Self',
		'meta_feedit.pi_flexform.feshowfields' => 'Creation show Fields',
		'meta_feedit.pi_flexform.fepreviewfields' =>'Preview Fields',
		'meta_feedit.pi_flexform.listMediaPlayer' =>'Show Media Player',
		'meta_feedit.pi_flexform.feeditfields' => 'Edit Fields',
		'meta_feedit.pi_flexform.noActions' => 'No actions',
		'meta_feedit.pi_flexform.noHeaders' => 'No headers',
		'meta_feedit.pi_flexform.cacheMode' => 'Cache Mode',
		
		'meta_feedit.pi_flexform.sheet_ajax' => 'AjaxParameters',
		'meta_feedit.pi_flexform.ajaxOn' => 'Activate WEB 2.0 Functionnality',
		'meta_feedit.pi_flexform.jqueryCompatMode' => 'Activate jQuery compatibility mode (for use with mootools, prototype, ...)',

		'meta_feedit.pi_flexform.cacheMode.noCache' => 'No Cache',
		'meta_feedit.pi_flexform.cacheMode.mixtCache' => 'Mixt Cache',
		'meta_feedit.pi_flexform.cacheMode.fullCache' => 'Full Cache',
		'meta_feedit.pi_flexform.calMode' => 'Calendar Mode',
		'meta_feedit.pi_flexform.calMode.default' => 'default',
		'meta_feedit.pi_flexform.calMode.dayView' => 'Day view',
		'meta_feedit.pi_flexform.calMode.weekView' => 'WeekView',
		'meta_feedit.pi_flexform.calMode.monthView' => 'Month view',
		'meta_feedit.pi_flexform.calMode.yearView' => 'Year view',
		'meta_feedit.pi_flexform.calMode.upcomingEventsView' => 'Upcoming events view',
		'meta_feedit.pi_flexform.calMode.fullCache' => 'WeekView',
		'meta_feedit.pi_flexform.T3SourceTreePid' => 'Source Tree to copy',
		'meta_feedit.pi_flexform.T3TreeTargetPid' => 'Tree copy target',
		'meta_feedit.pi_flexform.T3FEGroupsPID' => 'Page to store fe groups',
		'meta_feedit.pi_flexform.T3AdminUid' => 'BE user to use to copy',
		'meta_feedit.pi_flexform.T3TableHomePidField' => 'Field storing Copied Tree Pid',
		'meta_feedit.pi_flexform.enableColumns' => 'Use Enable Columns',
		'meta_feedit.pi_flexform.feeditshowfields' => 'Edit show Fields',
		'meta_feedit.pi_flexform.fecreatereadonlyfields' => 'Read Only Fields',
		'meta_feedit.pi_flexform.feeditreadonlyfields' => 'Read only fields  in edit mode',
		'meta_feedit.pi_flexform.ferequiredfields' => 'Required Fields',
		'meta_feedit.pi_flexform.feapprovefields' => 'Approve Fields',
		'meta_feedit.pi_flexform.feeditoverridevalues' => 'Edit Override Values',
		'meta_feedit.pi_flexform.fecreateoverridevalues' => 'Create Override Values',
		'meta_feedit.pi_flexform.fedeletefields' => 'Delete Fields',
		'meta_feedit.pi_flexform.fecruser_field' => 'User Id Field',
		'meta_feedit.pi_flexform.fecrgroup_field' => 'Group Id Field',
		'meta_feedit.pi_flexform.disableEdit' => 'Disable edit',
		'meta_feedit.pi_flexform.editUnique' => 'Edit unique',
		'meta_feedit.pi_flexform.menuLockPid' => 'List lock pid',
		'meta_feedit.pi_flexform.pagination' => 'Pagination',
		'meta_feedit.pi_flexform.pageSize' => 'Page size',
		'meta_feedit.pi_flexform.nbCols' => 'Nb cols table presentation',
		'meta_feedit.pi_flexform.maxPages' => 'Max Pages',
		'meta_feedit.pi_flexform.tabLabels' => 'Tab Labels (1 per line)',
		'meta_feedit.pi_flexform.fieldSort' => 'Field sorting',
		'meta_feedit.pi_flexform.listnobackbutton' => 'No Back Button',
		'meta_feedit.pi_flexform.listAltRows'=> 'Nb alternate row colors',
		'meta_feedit.pi_flexform.listsqlcalcfields' => 'SQL Calculated Fields',
		'meta_feedit.pi_flexform.listphpcalcfields' => 'PHP Calculated Fields',
		'meta_feedit.pi_flexform.listnodetail' => 'No group by detail',
		'meta_feedit.pi_flexform.listHavingString' => 'Having string',
		'meta_feedit.pi_flexform.debug' => 'Debug mode',
		'meta_feedit.pi_flexform.no_cache' => 'No cache',
		'meta_feedit.pi_flexform.searchBox' => 'Show Full Text Searchbox',
		'meta_feedit.pi_flexform.emailFrom' => 'From Mail',
		'meta_feedit.pi_flexform.sendAdminMail' => 'Send Admin Mail',
		'meta_feedit.pi_flexform.sendFEUserMail' => 'Send FE User Mail',
		'meta_feedit.pi_flexform.sendDataMail' => 'Send Data Mail',
		'meta_feedit.pi_flexform.dataMailField' => 'Mail Field for dataMail',
		'meta_feedit.pi_flexform.sendAdminInfoMail' => 'Send Admin Info Mail',
		'meta_feedit.pi_flexform.sendFEUserInfoMail' => 'Send FE User Info Mail',
		'meta_feedit.pi_flexform.sendDataInfoMail' => 'Send Data Info Mail',
		'meta_feedit.pi_flexform.emailFromName' => 'From Mail Name',
		'meta_feedit.pi_flexform.emailAdmin' => 'Admin Mail',
		'meta_feedit.pi_flexform.menuLockPid' => 'List lock pid',
		'meta_feedit.pi_flexform.divide2tabs' => 'Tab mode',
		'meta_feedit.pi_flexform.createPid' => 'Create Page PID',
		'meta_feedit.pi_flexform.groupByFields' => 'Group By Fields',
		'meta_feedit.pi_flexform.groupByFieldBreaks' => 'Group By Field Breaks',
		'meta_feedit.pi_flexform.orderByFields' => 'Order By Fields (default)',
		'meta_feedit.pi_flexform.sumFields' => 'Sum Fields',
		'meta_feedit.pi_flexform.editPid' => 'Edit Page PID',
		'meta_feedit.pi_flexform.checkT3Rights' => 'Check TYPO3 rights to edit/save/delete/...',
		
		// blogs -- begin
		'meta_feedit.pi_flexform.sheet_blogs' => 'Blogs',
		'meta_feedit.pi_flexform.allowComments' => 'Allow Commenting',
		'meta_feedit.pi_flexform.showComments' => 'Show Comments',
		'meta_feedit.pi_flexform.blogtemplate' => 'Blog Template',
		'meta_feedit.pi_flexform.blogCaptcha' => 'Captcha spam protect',
		'meta_feedit.pi_flexform.rowField' => 'Row Field',
  	'meta_feedit.pi_flexform.colField' => 'Col Field',
  	'meta_feedit.pi_flexform.beginDateField' => 'Begin Date Field',
  	'meta_feedit.pi_flexform.endDateField' => 'End Date Field',
  	
		//general  -- begin
		'meta_feedit.pi_flexform.sheet_generalTemplate' => 'General templates',
		'meta_feedit.pi_flexform.generalAuthTemplate' => 'Authorisation template',
		'meta_feedit.pi_flexform.generalNoPermTemplate' => 'No permission template',
		//general Templates -- end
		
		//--------------------------------------------------------------------------------------------------------//
		'meta_feedit.pi_flexform.sheet_TemplatePDF' => 'Template PDF',
		'meta_feedit.pi_flexform.TemplatePDF' => 'Template PDF for lists',
		'meta_feedit.pi_flexform.TemplatePDFDet' => 'Template PDF for detail',
		'meta_feedit.pi_flexform.TemplatePDFTab' => 'Template PDF for tables',
		'meta_feedit.pi_flexform.sheet_TemplateCSV' => 'Template CSV',
		'meta_feedit.pi_flexform.TemplateCSV' => 'Template CSV',
		'meta_feedit.pi_flexform.sheet_TemplateExcel' => 'Template Excel',
		'meta_feedit.pi_flexform.TemplateExcel' => 'Template Excel',

		//list Templates -- begin
		'meta_feedit.pi_flexform.sheet_list' => 'List',
		'meta_feedit.pi_flexform.sheet_listTemplate' => 'List templates',
		'meta_feedit.pi_flexform.listItemTemplate' => 'Item template',
		'meta_feedit.pi_flexform.listNoItemTemplate' => 'No item template',
		'meta_feedit.pi_flexform.listrecordactions' => 'List record actions',
		'meta_feedit.pi_flexform.listJumpPageOnGroupBy' => 'Jump page on group by',
		'meta_feedit.pi_flexform.listWhereString' => 'Where String',
		'meta_feedit.pi_flexform.listOrderByString' => 'Post Order By String',
		'meta_feedit.pi_flexform.listPreOrderByString' => 'Pre Order By String',
		'meta_feedit.pi_flexform.listExtraFields' => 'Extra Fields (not shown)',
		'meta_feedit.pi_flexform.listlangmarks' => 'Language marks (lg.label=val)',
		'meta_feedit.pi_flexform.listPid' => 'List Page PID',
		'meta_feedit.pi_flexform.listFields' => 'List show fields',
		'meta_feedit.pi_flexform.listHiddenFields' => 'List extra fields',
		'meta_feedit.pi_flexform.listMediaPlayer' =>'Show Media Player',

		//list Templates -- end
		//grid Templates -- begin
		'meta_feedit.pi_flexform.sheet_grid' => 'Data grid',
		'meta_feedit.pi_flexform.sheet_gridTemplate' => 'Grid template',
		'meta_feedit.pi_flexform.gridItemTemplate' => 'Item template',
		'meta_feedit.pi_flexform.gridNoItemTemplate' => 'No item template',
		'meta_feedit.pi_flexform.gridrecordactions' => 'Grid record actions',
		'meta_feedit.pi_flexform.gridWhereString' => 'Where String',
		'meta_feedit.pi_flexform.gridOrderByString' => 'Order By String',
		'meta_feedit.pi_flexform.gridExtraFields' => 'Extra Fields (not shown)',
		'meta_feedit.pi_flexform.gridLangmarks' => 'Language marks (lg.label=val)',
		'meta_feedit.pi_flexform.gridPid' => 'Grid Page Pid',
		'meta_feedit.pi_flexform.gridFields' => 'Grid show fields',
		'meta_feedit.pi_flexform.gridHiddenFields' => 'Grid extra fields',
		'meta_feedit.pi_flexform.gridExportPDF' => 'Export PDF',
		'meta_feedit.pi_flexform.gridExportCSV' => 'Export CSV',
		'meta_feedit.pi_flexform.gridExportExcel' => 'Export Excel',
		'meta_feedit.pi_flexform.gridEuros' => 'Display numeric values in euros',
		'meta_feedit.pi_flexform.gridMediaPlayer' =>'Show Media Player',
    'meta_feedit.pi_flexform.gridOrderByFields' => 'Order By Fields',
	  'meta_feedit.pi_flexform.gridCols' => 'Nb Cols',
	  'meta_feedit.pi_flexform.gridRows' => 'Nb Rows',
	  'meta_feedit.pi_flexform.gridRowField' => 'Row Field',
	  'meta_feedit.pi_flexform.gridColField' => 'Col Field',
    'meta_feedit.pi_flexform.gridBackPagePid' => 'Back Page Pid',
		'meta_feedit.pi_flexform.gridrUJoinField' => 'rU Join Field',
    
		//create Templates -- begin
		
		'meta_feedit.pi_flexform.sheet_createTemplate' => 'Create templates',
		'meta_feedit.pi_flexform.createScreenTemplate' => 'Create screen template',
		'meta_feedit.pi_flexform.createPreviewTemplate' => 'Preview template',
		'meta_feedit.pi_flexform.createScreenLoginTemplate' => 'Create screen login template',
		'meta_feedit.pi_flexform.createPreviewLoginTemplate' => 'Preview login template',
		'meta_feedit.pi_flexform.createSavedTemplate' => 'Saved template',
		'meta_feedit.pi_flexform.createUserNotifyMailTemplate' => 'User notify mail template',
		'meta_feedit.pi_flexform.createDataNotifyMailTemplate' => 'Data notify mail template',
		'meta_feedit.pi_flexform.createAdminNotifyMailTemplate' => 'Admin notify mail template',
		'meta_feedit.pi_flexform.createAdminValidMailTemplate' => 'Admin valid mail template',
		'meta_feedit.pi_flexform.createUserNotifyOkMailTemplate' => 'User notify OK mail template',
		'meta_feedit.pi_flexform.createUserNotifyKoMailTemplate' => 'User notify KO mail template',
		//create Templates -- end
		
		//edit Templates -- begin
		'meta_feedit.pi_flexform.sheet_editTemplate' => 'Edit templates',
		'meta_feedit.pi_flexform.editScreenTemplate' => 'Edit screen template',
		'meta_feedit.pi_flexform.editPreviewTemplate' => 'Preview template',
		'meta_feedit.pi_flexform.editSavedTemplate' => 'Saved template',
		'meta_feedit.pi_flexform.editUserNotifyMailTemplate' => 'User notify mail template',
		'meta_feedit.pi_flexform.editAdminNotifyMailTemplate' => 'Admin notify mail template',
		'meta_feedit.pi_flexform.editDataNotifyMailTemplate' => 'Data notify mail template',
		'meta_feedit.pi_flexform.editAdminValidMailTemplate' => 'Admin valid mail template',
		'meta_feedit.pi_flexform.editUserNotifyOkMailTemplate' => 'User notify OK mail template',
		'meta_feedit.pi_flexform.editUserNotifyKoMailTemplate' => 'User notify KO mail template',
		'meta_feedit.pi_flexform.editrecordactions' => 'Edit record actions',

		//edit Templates -- end
		
		//delete Templates -- begin
		'meta_feedit.pi_flexform.sheet_deleteTemplate' => 'Delete templates',
		'meta_feedit.pi_flexform.deletePreviewTemplate' => 'Preview template',
		'meta_feedit.pi_flexform.deleteSavedTemplate' => 'Saved template',
		'meta_feedit.pi_flexform.deleteUserNotifyMailTemplate' => 'User notify mail template',
		'meta_feedit.pi_flexform.deleteAdminNotifyMailTemplate' => 'Admin notify mail template',
		//delete Templates -- end
		
		//setFixed Templates -- begin
		'meta_feedit.pi_flexform.setFixedTemplate' => 'Set fixed templates',
		'meta_feedit.pi_flexform.setFixedOkTemplate' => 'Ok template',
		'meta_feedit.pi_flexform.setFixedOkDeleteTemplate' => 'Ok delete template',
		'meta_feedit.pi_flexform.setFixedFailedTemplate' => 'Failed template',
		
		//setFixed Templates -- end
		'meta_feedit.pi_flexform.editStatusScreen' => 'Show status screen',
		'meta_feedit.pi_flexform.createStatusScreen' => 'Show status screen',
		'meta_feedit.pi_flexform.deleteStatusScreen' => 'Show status screen',
		'meta_feedit.pi_flexform.createPreview' => 'Create Preview',
		'meta_feedit.pi_flexform.fetemplate' => 'Template',
		'meta_feedit.pi_flexform.sheet_preview' => 'Preview',
		'meta_feedit.pi_flexform.sheet_setfixed' => 'Mails',
		'meta_feedit.pi_flexform.sheet_delete' => 'Delete',
		'meta_feedit.pi_flexform.useTemplate' => 'use template',
		'meta_feedit.pi_flexform.extTables' => 'Extension TCAs to take into account',
		'meta_feedit.pi_flexform.fe_userEditSelf' => 'Can user edit his info',
		'meta_feedit.pi_flexform.template_file' => 'Use this template file instead of default',
		'meta_feedit.pi_flexform.generateTemplate' => 'Generate Template in Browser',
		'meta_feedit.pi_flexform.pluginId' => 'Plugin Id',
		
		'meta_feedit.pi_flexform.pdf' => 'PDF',
		'meta_feedit.pi_flexform.csv' => 'Csv',
		'meta_feedit.pi_flexform.excel' => 'Excel',
		'meta_feedit.pi_flexform.euros' => 'Display numeric valuees in Euros',
	),
	'dk' => Array (
	),
	'de' => Array (
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
   	'meta_feedit.pi_flexform.gridAjax' => 'Grille',
		'meta_feedit.pi_flexform.gridEdit' => 'Edition',
		'meta_feedit.pi_flexform.sheet_general' => 'Configuration g�n�rale',
		'meta_feedit.pi_flexform.sheet_create' => 'Cr�ation',
		'meta_feedit.pi_flexform.sheet_edit' => 'Edition',
		'meta_feedit.pi_flexform.defaultCmd' => 'Commande par d�faut',
		'meta_feedit.pi_flexform.defaultCmd.create' => 'Cr�ation',
		'meta_feedit.pi_flexform.defaultCmd.edit' => 'Edition',
		'meta_feedit.pi_flexform.page' => 'Page with records', //
		'meta_feedit.pi_flexform.disableDelete' => 'D�sactiver la suppression',
		'meta_feedit.pi_flexform.disableEditDelete' => 'D�sactiver la suppression � l\'�dition', //?
		'meta_feedit.pi_flexform.requireLogin' => 'Requi�re que l\'utilisateur soit connect�',
		'meta_feedit.pi_flexform.no_header' => 'Ne pas afficher les ent�tes automatiquement g�n�r�es',
		'meta_feedit.pi_flexform.show_help_icons' => 'Afficher les icones d\'aide (si disponible)',
		'meta_feedit.pi_flexform.allowedGroups' => 'Groupes autoris�s � �diter', //
		'meta_feedit.pi_flexform.clearCacheOfPages' => 'Pages dont le cache doit �tre vid� apr�s mise � jour', //
		'meta_feedit.pi_flexform.disableCreate' => 'D�sactiver la cr�ation',
		'meta_feedit.pi_flexform.noSpecialLoginForm' => 'Show no special form when logged in',
		'meta_feedit.pi_flexform.fetable' => 'Table � �diter',
		'meta_feedit.pi_flexform.backPagePid' => 'Back Page Pid',
		'meta_feedit.pi_flexform.fecreatefields' => 'Champs remont�s en mode cr�ation',
		'meta_feedit.pi_flexform.fe_userOwnSelf' => 'Fe User Own Self',
		'meta_feedit.pi_flexform.feshowfields' => 'Champs affich�s',
		'meta_feedit.pi_flexform.fepreviewfields' =>'Champs affcih�s en mode pr�visualisation',
		'meta_feedit.pi_flexform.feeditfields' => 'Champs remont�s en mode �dition',
		'meta_feedit.pi_flexform.feeditshowfields' => 'Champs affich�s en mode �dition',
		'meta_feedit.pi_flexform.feeditreadonlyfields' => 'Read only fields  in edit mode',
		'meta_feedit.pi_flexform.ferequiredfields' => 'Champs requis',
		'meta_feedit.pi_flexform.feapprovefields' => 'Approve Fields',
		'meta_feedit.pi_flexform.feeditoverridevalues' => 'Edit Override Values',
		'meta_feedit.pi_flexform.fecreateoverridevalues' => 'Create Override Values',
		'meta_feedit.pi_flexform.feeditevalvalues' => 'Edit eval Values',
		'meta_feedit.pi_flexform.fecreateevalvalues' => 'Create eval Values',
		'meta_feedit.pi_flexform.fedeletefields' => 'Delete Fields',
		'meta_feedit.pi_flexform.fecruser_field' => 'User Id Field',
		'meta_feedit.pi_flexform.fecrgroup_field' => 'Group Id Field',
		'meta_feedit.pi_flexform.disableEdit' => 'Disable edit',
		'meta_feedit.pi_flexform.hideCreate' => 'Cacher la cr�ation',
		'meta_feedit.pi_flexform.hideEdit' => 'Cacher l\'edition',
		'meta_feedit.pi_flexform.hideDelete' => 'Cacher la suppression',
		'meta_feedit.pi_flexform.editUnique' => 'Edit unique',
		'meta_feedit.pi_flexform.editDontUseHidden' => 'Don\'t use hidden check on MM edit',
		'meta_feedit.pi_flexform.editDontUseDate' => 'Don\'t use date check on MM edit',
		'meta_feedit.pi_flexform.pdf' => 'PDF',
		'meta_feedit.pi_flexform.csv' => 'Csv',
		'meta_feedit.pi_flexform.excel' => 'Excel',
		'meta_feedit.pi_flexform.euros' => 'Affichage des valeurs num�riques en Euros',
		'meta_feedit.pi_flexform.menuLockPid' => 'List lock pid',
		'meta_feedit.pi_flexform.pagination' => 'Pagination',
		'meta_feedit.pi_flexform.pageSize' => 'Page size',
		'meta_feedit.pi_flexform.maxPages' => 'Max Pages',
		'meta_feedit.pi_flexform.tabLabels' => 'Lib�ll�s d\'onglets (1 par ligne)',
		'meta_feedit.pi_flexform.fieldSort' => 'Tri par champ',
		'meta_feedit.pi_flexform.debug' => 'Mode Debug',
		'meta_feedit.pi_flexform.listnobackbutton' => 'Pas de bouton retour',
		'meta_feedit.pi_flexform.listAltRows'=> 'Nb couleurs de lignes alternantes',
		'meta_feedit.pi_flexform.listsqlcalcfields' => 'Champs calcul�s SQL',
		'meta_feedit.pi_flexform.listphpcalcfields' => 'Champs calcul�s PHP',
		'meta_feedit.pi_flexform.no_cache' => 'Pas de cache',
		'meta_feedit.pi_flexform.searchBox' => 'Show Full Text Searchbox',
		'meta_feedit.pi_flexform.emailFrom' => 'Mail Expediteur',
		'meta_feedit.pi_flexform.sendAdminMail' => 'Send Admin Mail',
		'meta_feedit.pi_flexform.dataMailField' => 'Mail Field for dataMail',
		'meta_feedit.pi_flexform.emailFromName' => 'From Mail Name',
		'meta_feedit.pi_flexform.emailAdmin' => 'Admin Mail',
		'meta_feedit.pi_flexform.menuLockPid' => 'List lock pid',
		'meta_feedit.pi_flexform.divide2tabs' => 'Tab mode',
		'meta_feedit.pi_flexform.createPid' => 'Create Page PID',
		'meta_feedit.pi_flexform.listFields' => 'List fields',
		'meta_feedit.pi_flexform.listPid' => 'List Page PID',
		'meta_feedit.pi_flexform.editPid' => 'Edit Page PID',
		'meta_feedit.pi_flexform.checkT3Rights' => 'Check TYPO3 rights to edit/save/delete/...',
		'meta_feedit.pi_flexform.editPreview' => 'Edit Preview',
		//create Mail Templates -- begin
		'meta_feedit.pi_flexform.createTemplate' => 'Create Templates',
		'meta_feedit.pi_flexform.createSavedTemplate' => 'Saved Templates',
		'meta_feedit.pi_flexform.createUserNotifyMailTemplate' => 'User Notify Mail Templates',
		'meta_feedit.pi_flexform.createAdminNotifyMailTemplate' => 'Admin Notify Mail Templates',
		'meta_feedit.pi_flexform.createAdminValidMailTemplate' => 'Admin Valid Mail Templates',
		'meta_feedit.pi_flexform.createUserNotifyOkMailTemplate' => 'User Notify OK Mail Templates',
		'meta_feedit.pi_flexform.createUserNotifyKoMailTemplate' => 'User Notify KO Mail Templates',
		//create Mail Templates -- end
		//edit Mail Templates -- begin
		'meta_feedit.pi_flexform.editTemplate' => 'Edit Templates',
		'meta_feedit.pi_flexform.editSavedTemplate' => 'Saved Templates',
		'meta_feedit.pi_flexform.editUserNotifyMailTemplate' => 'User Notify Mail Templates',
		'meta_feedit.pi_flexform.editAdminNotifyMailTemplate' => 'Admin Notify Mail Templates',
		'meta_feedit.pi_flexform.editAdminValidMailTemplate' => 'Admin Valid Mail Templates',
		'meta_feedit.pi_flexform.editUserNotifyOkMailTemplate' => 'User Notify OK Mail Templates',
		'meta_feedit.pi_flexform.editUserNotifyKoMailTemplate' => 'User Notify KO Mail Templates',
		//edit Mail Templates -- end
		//delete Mail Templates -- begin
		'meta_feedit.pi_flexform.deleteTemplate' => 'Delete Templates',
		'meta_feedit.pi_flexform.deleteSavedTemplate' => 'Saved Templates',
		'meta_feedit.pi_flexform.deleteUserNotifyMailTemplate' => 'User Notify Mail Templates',
		'meta_feedit.pi_flexform.deleteAdminNotifyMailTemplate' => 'Admin Notify Mail Templates',
		//delete Mail Templates -- end
		//setFixed Templates -- begin
		'meta_feedit.pi_flexform.setFixedTemplate' => 'Set Fixed Templates',
		'meta_feedit.pi_flexform.setFixedOkTemplate' => 'Ok Templates',
		'meta_feedit.pi_flexform.setFixedOkDeleteTemplate' => 'Ok Delete Templates',
		'meta_feedit.pi_flexform.setFixedFailedTemplate' => 'Gabarit d\'echec',
		//setFixed Templates -- end
		'meta_feedit.pi_flexform.editrecordactions' => 'Actions en mode �dition',
	
		'meta_feedit.pi_flexform.editStatusScreen' => 'Afficher ecran de confirmation',
		'meta_feedit.pi_flexform.createStatusScreen' => 'Afficher ecran de confirmation',
		'meta_feedit.pi_flexform.deleteStatusScreen' => 'Afficher ecran de confirmation',
		'meta_feedit.pi_flexform.createPreview' => 'Create Preview',
		'meta_feedit.pi_flexform.fetemplate' => 'Gabarit',
		'meta_feedit.pi_flexform.sheet_preview' => 'Preview',
		'meta_feedit.pi_flexform.sheet_setfixed' => 'Mails',
		'meta_feedit.pi_flexform.sheet_delete' => 'Delete',
		'meta_feedit.pi_flexform.sheet_list' => 'List',
		'meta_feedit.pi_flexform.useTemplate' => 'use template',
		'meta_feedit.pi_flexform.extTables' => 'Extension TCAs to take into account',
		'meta_feedit.pi_flexform.fe_userEditSelf' => 'Can user edit his info',
		'meta_feedit.pi_flexform.editDontUseHidden' => 'Don\'t hide Hidden Rows',
		'meta_feedit.pi_flexform.editDontUseDate' => 'Don\'t hide outdated Rows',
		'meta_feedit.pi_flexform.template_file' => 'Use this template file instead of default',
		'meta_feedit.pi_flexform.generateTemplate' => 'Generate Template in Browser',
		'meta_feedit.pi_flexform.TemplatePDF' => 'Gabarit PDF pour les listes',
		'meta_feedit.pi_flexform.TemplatePDFDet' => 'Gabarit PDF pour la vue en détail',
		'meta_feedit.pi_flexform.TemplatePDFTab' => 'Gabarit PDF pour les tabaleaux',

	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>
